version: "3"

services:
  api-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-server
    restart: unless-stopped
    networks:
      - app-network
    ports:
      - "3000:3000"

networks:
  app-network:
    driver: bridge
