apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-server
  template:
    metadata:
      labels:
        app: api-server
    spec:
      containers:
        - name: api-server
          image: idirch/microservices-kubernets
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
